### ISSUE TITLE
'fatal: Unable to create '.../.git/index.lock': File exists.

### ISSUE THREAD

**Issue by patricksheehan** [kynan/nbstripout#103]
When running `nbstripout` via pre-commit I get the following error:

> Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: Unable to create 'REPO_PATH/.git/index.lock': File exists.

Has anyone run into this? I've tried wiping my pre-commit installation, wiping the local repo, etc.

**Comment by kynan** [comment]
Is this reproducible? Did you confirm you don't actually have any other process running that might try to modify the git index as the error message suggests?

**Comment by patricksheehan** [comment]
Yeah it's quite confusing to me. I've tried:
- Killing any other git processes
- Doing a fresh wipe on the repo itself
- Running on other branches
- Cleaning/uninstalling/reinstalling pre-commit
- Restarting the computer itself (for fun)

**Comment by patricksheehan** [comment]
One more detail is that the command-line version does work as intended

**Comment by patricksheehan** [comment]
Ok this seems to have resolved itself while I was doing some other things. Not sure what the state was that caused it, but I'll close this out!

**Comment by SimonBiggs** [comment]
Interestingly, I am getting this error when running nbstripout within pre-commit on GitHub actions:

https://github.com/pymedphys/pymedphys/pull/486/checks?check_run_id=232417630#step:4:64

Based on the following action:

https://github.com/pymedphys/pymedphys/blob/4a9d63ad6859e8d31ee2e3f277932233f8a69fcb/.github/workflows/main.yml#L5-L19

**Comment by kynan** [comment]
@SimonBiggs have you had a chance to investigate further?
