### ISSUE TITLE
Cut 0.3.7 to make nbstripout work on systems with old versions of git?

### ISSUE THREAD

**Issue by garborg** [kynan/nbstripout#109]
Due to https://github.com/pre-commit/pre-commit/issues/1211, pre-commit integration is not working for me on systems with old versions of git (because the latest tag is older than pre-commit integration, and pre-commit can't reference shas newer than the oldest tag if system git is old).

A tag would work around the pre-commit limitation for me and any other affected users.

**Comment by kynan** [comment]
Done! Please close if that resolves your issue.

**Comment by garborg** [comment]
It does, thank you!
