### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by kynan** [kynan/nbstripout#12]
We currently only store the version in `setup.py`, which is not very useful. There should be a switch `nbstripout --version` and/or `nbstripout version`.

Options for implementing this include:
* [Create a `version.py` module and load in `setup.py` via `execfile`](http://stackoverflow.com/a/2073599) (would require turning `nbstripout` into a package)
* Use [versioneer](https://github.com/warner/python-versioneer)

Any thoughts @mforbes @michaelaye?

**Comment by mforbes** [comment]
I still don't have a definitive answer for how to do this.  Another option is to include a variable ``__VERSION__`` at the top of the ``nbstripout.py`` file and then read this in, or just manually change both that and the contents in ``setup.py``.

**Comment by michaelaye** [comment]
The python packaging guide offers 7 methods for doing this, just pick the one that you think fits best to your project:
https://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/

**Comment by michaelaye** [comment]
but `bumpversion` and `versioneer` are certainly worth a look as well, depending on how easy they are to setup.

**Comment by mforbes** [comment]
I tried `bumpversion` once, but found it not intunitive enough to use naturally when I only used it sporadically, so I stopped.  That was a while ago - it might be better now.  The idea is nice.

**Comment by michaelaye** [comment]
I had a quick look at versioneer, sounds easy enough to use after a few clear installation steps.

**Comment by kynan** [comment]
I have used versioneer in the past. It is quite "heavy" though, so I'm not sure it's worth the hassle for such a simple project.

**Comment by kynan** [comment]
@michaelaye Thanks for pointing out the various options. For something as simple as nbstripout maybe bumpversion is enough. I'll give it a go.

**Comment by kynan** [comment]
OK, reasonably happy with bumpversion from a quick test apart from missing support annotated tags: peritus/bumpversion#2, peritus/bumpversion#58, peritus/bumpversion#74.

**Comment by kynan** [comment]
Since I'm impatient I simply installed the bumpversion branch pr'ed in peritus/bumpversion#58:

    pip install git+https://github.com/ekohl/bumpversion@annotated-tags
