### ISSUE TITLE
Pre-commit Jupyter type installation issue.

### ISSUE THREAD

**Issue by jcmuddle** [kynan/nbstripout#132]
When using nbstripout with pre-commit I experience the following error after running `pre-commit autoupdate`

```
Updating https://github.com/kynan/nbstripout ... 
==> File /home/jmuddle/.cache/pre-commit/repokfgntqfa/.pre-commit-hooks.yaml
==> At Hook(id='nbstripout')
==> At key: types
==> At index 0
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
```

This seems to be related to the most recent change to .pre-commit-hooks.yaml.

I resolved the issue by installing the identify library. https://github.com/chriskuehl/identify

This primarily seems to be an issue with pre-commit not installing the necessary dependencies, but it might be useful to update the doc, but at a minimum, this issue might help others.

**Comment by kynan** [comment]
afaict, pre-commit [depends on identify](https://github.com/pre-commit/pre-commit/blob/master/setup.cfg#L26). Do you have a way to reproduce the issue?

**Comment by kynan** [comment]
@jcmuddle Are you still seeing this issue?

**Comment by jcmuddle** [comment]
@kynan Sorry for the late reply. I am no longer seeing this issue. Thank you for the work you have put into this tool.
