### ISSUE TITLE
git-hook applies nb-stripout on unstaged notebooks

### ISSUE THREAD

**Issue by krlng** [kynan/nbstripout#137]
Using nb-stripout (v 0.3.8) as a git-hook will strip-out content of unstaged, not committed notebooks as soon as there is at least one notebook which gets committed. In my opinion, files which are not staged should not get touched or this should be documented otherwise.

**Comment by kynan** [comment]
Can you confirm what your setup is? Are you using the `pre-commit` framework with a `.pre-commit-config.yaml` as documented in the [README](https://github.com/kynan/nbstripout#using-nbstripout-as-a-pre-commit-hook)? A reproducible test case would also be super useful.

Note that the `pre-commit` framework [stashes unstaged changes](https://pre-commit.com/#pre-commit-during-commits) while the hook is running.

**Comment by kynan** [comment]
I think this is similar to #121. See my [comment](https://github.com/kynan/nbstripout/issues/121#issuecomment-817388175) with the log of a test which produced the exact result I expected, using pre-commit 2.12.0.

**Comment by kynan** [comment]
@krlng is this still an issue for you?

**Comment by krlng** [comment]
Hi :) I have no idea, not using it anymore. Will close it.
