### ISSUE TITLE
Tags but not releases; rev: master is not supported

### ISSUE THREAD

**Issue by dmyersturnbull** [kynan/nbstripout#145]
This is a fantastic package! Thanks for continuing to update it.

I was originally using `v0.3.1` from the [releases](https://github.com/kynan/nbstripout/releases), but `0.3.9` is available as a [tag](https://github.com/kynan/nbstripout/tags). I had just assumed that 0.3.1 was the most recent! Is there a reason why there are no releases corresponding to recent tags?

Related, the example in the readme uses `rev: master`, which causes pre-commit to emit this warning:

```
Warning:  The 'rev' field of repo 'https://github.com/kynan/nbstripout' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.
```

**Comment by kynan** [comment]
> I was originally using `v0.3.1` from the [releases](https://github.com/kynan/nbstripout/releases), but `0.3.9` is available as a [tag](https://github.com/kynan/nbstripout/tags). I had just assumed that 0.3.1 was the most recent! Is there a reason why there are no releases corresponding to recent tags?

None other than oversight on my part. I've turned all tags into "proper" releases now, thanks for pointing this out.

Is there a reason you're not installing via `pip` or `conda`?

> Related, the example in the readme uses `rev: master`, which causes pre-commit to emit this warning:
> 
> ```
> Warning:  The 'rev' field of repo 'https://github.com/kynan/nbstripout' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.
> ```

I think I was just being lazy and didn't want to forget updating to the latest tag, but I can just configure `bumpversion` to do that for me. I'll push a fix, thanks for flagging.
