### ISSUE TITLE
dry run seems to always print that a file would be changed

### ISSUE THREAD

**Issue by alonme** [kynan/nbstripout#152]
I noticed that when using dry_run, all files are always printed as if they would be changed.

Looking at the code briefly, it does seem like this is what happens.

**Comment by kynan** [comment]
> all files are always printed as if they would be changed

Can you clarify what you mean? What are "all files" here?

**Comment by alonme** [comment]
Yes, sorry for being unclear.

every file that is passed to nbstripout will print.
`Dry run: would have stripped {file}`

this happens even if a strip a file and then right after that run a dry run.

my expectation is that only files that would have been changed if a "wet run" would have been used - would be printed

**Comment by alonme** [comment]
Thanks.

Just so i understand - what is the current value of the dry-run option?

**Comment by kynan** [comment]
It will tell you which files are in scope / would be touched. I agree that your definition is more useful.

**Comment by joaonc** [comment]
Could this be related to this other issue? https://github.com/kynan/nbstripout/issues/160

**Comment by kynan** [comment]
@joaonc only tangentially. This request is about turning `--dry-run` into an "actual" dry run and only report if any changes would have been made.

**Comment by kynan** [comment]
@alonme Would you be interested in implementing this?

**Comment by swateek** [comment]
I am facing trouble here, I'll want to give this a try @kynan

**Comment by kynan** [comment]
@swateek sure! You'd need to change [this line](https://github.com/kynan/nbstripout/blob/master/nbstripout/_nbstripout.py#L474) to not overwrite the notebook and then in the following `if args.dry_run:` block you'd need to check if any changes were applied and then only output if there is a diff. You should also do this for the Zeppelin notebook type above. Is this enough to get you started?

**Comment by swateek** [comment]
let me try this out!

**Comment by kynan** [comment]
@swateek Are you still interested in working on this? Note that you'd be able to reuse @jspaezp's work to add a `--verify` flag, see #153, #195.

**Comment by kynan** [comment]
Actually, never mind, it's now a trivial change, so I'll fix that for 0.8.1 🎉
