### ISSUE TITLE
Add an option to return an error code if any files have/should be changed

### ISSUE THREAD

**Issue by alonme** [kynan/nbstripout#153]
In order to use this tool in CI, it would be useful if it could return an error code when a file has been changed/ would have been changed (when using dry_run)

**Comment by kynan** [comment]
For use in CI you probably want to use `nbstripout` as a [pre-commit hook](https://github.com/kynan/nbstripout#using-nbstripout-as-a-pre-commit-hook).

**Comment by alonme** [comment]
I am not using (and currently cannot use) [pre-commit ci](https://pre-commit.ci/).

Also - i don't want to alter files in my CI (server side, not locally before commits).

So i need to get some indication regarding if files were changed, which is AFAIU not currently available from the tool?

**Comment by yliederNY** [comment]
It would be awesome to have this option.

**Comment by kynan** [comment]
Feel like contributing this feature @yliederNY ? :)

**Comment by kynan** [comment]
@alonme @yliederNY one of you interested in working on this?

**Comment by jspaezp** [comment]
Hello there!

I like the idea of a `--verify` flag! I will try to make a PR for it sometime soon!
Just so we are clear, the. --verify would act as dry run but exit with status 1 when at least one of the files would have been stripped, and should be consistent to --dry-run in terms of stdout/stderr, right?

best!

**Comment by kynan** [comment]
@jspaezp Yes, what you describe sounds reasonable to me 👍🏽

**Comment by kmcentush** [comment]
Also would love this functionality.

**Comment by jspaezp** [comment]
I looked into it but with the current structure it leads to a lot of branching. It is doable but without some refactoring the ending code is very ugly.

**Comment by kynan** [comment]
Thanks @jspaezp for looking into this! As mentioned on your PR it's unfortunately not currently in a reviewable state. Could you please rebase on the tip of main?

**Comment by jspaezp** [comment]
Just sent a PR with the new main (after the refactor done it was a lot easier to add the feature, thanks for the code cleanup!)
