### ISSUE TITLE
Should be agnosting on trailing blank lines

### ISSUE THREAD

**Issue by joaonc** [kynan/nbstripout#160]
`nbstripout` is opinionated on _not_ having a trailing blank line, so if the only difference is that there's a blank line at the end, `nbstripout` will remove it.

This causes conflicts on editors that have options to add/remove blank lines at the end of files (almost all nowadays) and causes the pre-commit action to always fail b/c my editor adds a line on auto-save and then `nbstripout` removes it.

`nbstripout` should either have an option to add / not add a blank line at the end of the file _or_ detect what's there before running and leave the same way.

![image](https://user-images.githubusercontent.com/11450769/139513457-1d787bfa-672e-41ad-9733-6fc8b7681dfd.png)

**Comment by kynan** [comment]
It's not `nbstripout` being opinionated here, it's `nbformat`, as that's what we're using to write the notebook to file. Scanning the `nbformat` implementation I can't find a flag that would append a newline. I'd happily accept a pull request if you'd like to work on this @joaonc ?

**Comment by kynan** [comment]
This is unfortunately also not as simple as it may sound: `nbstripout` tries it utmost to not modify anything about the notebook except the output. In particular it tries to preserve system-specific newline characters. Thus when appending an extra newline at the end you need to make sure to pick the "right one".

**Comment by maciejb** [comment]
This issue seems to pose an additional challenge with PyCharm when `nbstripout` is used as a pre-commit hook. The two  fight back and forth adding and removing a blank line, making it impossible to do the commit within their GUI.

**Comment by kynan** [comment]
That is annoying :( @maciejb is PyCharm insisting on a trailing newline with no option to turn this off?

**Comment by joaonc** [comment]
PyCharm does have an option to turn on/off EOF cleanup (see image in the description of this issue). However, other tools such as `black`, some `pre-commit` hooks and other linters also add the new line at EOF and that's pretty standard.

Would be great if `nbstribpout` would do one of:
* Have a newline at EOF
* Not add/remove newline if no other changes are required
* Have an option on what to do at EOF (end with newline or not)

**Comment by kynan** [comment]
I understand the pain, however as [explained](https://github.com/kynan/nbstripout/issues/160#issuecomment-1003746527) this really is an `nbformat` issue, not an `nbstripout` issue and as such I have no intention to address this in `nbstripout`. Sorry!

**Comment by kynan** [comment]
Based on @maciejb last comment I'll close this as wontfix. Please reopen if new information emerges.
