### ISSUE TITLE
Doesn't strip out pycharm metadata

### ISSUE THREAD

**Issue by SiddhantSadangi** [kynan/nbstripout#163]
PyCharm adds the below metadata to markdown cells whenever a notebook is opened in its renderer:
```
   "metadata": {
    "pycharm": {
     "name": "#%% md\n"
    }
   },
```

This is not stripped by nbstripout even when using the `nbstripout --extra-keys "metadata.pycharm"` or `git config --system filter.nbstripout.extrakeys 'metadata.pycharm'` options

**Comment by kynan** [comment]
I'm not a PyCharm user so I don't know how PyCharm interacts with Git. Are you using Git in PyCharm or on the command line?

**Comment by SiddhantSadangi** [comment]
PyCharm, but don't think that would make any difference as commands are sent to the command line anyway

**Comment by kynan** [comment]
It would make a difference if PyCharm appends this metadata *after* its interaction with Git, in which case there's nothing `nbstripout` could do. I'll try to reproduce this.

**Comment by kynan** [comment]
Turns out only PyCharm Professional supports notebooks in edit mode, so I can't reproduce this.

**Comment by SiddhantSadangi** [comment]
PyCharm appends this metadata as soon as a notebook is opened in edit mode.
To reproduce, can you open a notebook as text and manually append this to it? Or I can attach a notebook with this appended

**Comment by kynan** [comment]
If you could attach a test case that would be really helpful.

**Comment by SiddhantSadangi** [comment]
Attaching three versions of the same notebook. The first is the original - clean with no metadata and output, second is after running in pycharm (you can see the pycharm metadata attributes added on openings the notebook in a text editor); third is after stripping out the output using `nbstripout --extra-keys "metadata.pycharm"  3_output_stripped.ipynb`.. the output has been stripped, but the pycharm tags haven't

[notebooks.zip](https://github.com/kynan/nbstripout/files/8549607/notebooks.zip)

**Comment by SiddhantSadangi** [comment]
@kentavv - thank you. Confirming that this works
