### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by alexsanduk** [kynan/nbstripout#164]
Hey Florian, thanks a lot for this amazing project. It helps me on a daily basis to keep my notebooks clean.
You have recently added very useful flag `--drop-tagged`. Any chance that you can make a new release that would support it. Moreover last release was quite some time ago, over a year 😓

**Comment by kynan** [comment]
Fair point, a new release is long overdue! Will do.

**Comment by kynan** [comment]
FYI, 0.6.0 is out!
