### ISSUE TITLE
Replace cram with prysk

### ISSUE THREAD

**Issue by kynan** [kynan/nbstripout#165]
[Prysk](https://www.prysk.net) (https://github.com/Nicoretti/prysk) seems to be a new-ish, maintained fork of https://github.com/brodie/cram. Would be good to evaluate if this addresses some of the long-standing issues with cram e.g. Windows newlines.

**Comment by arobrien** [comment]
@kynan I had a go at getting Prysk to work, and I kept on coming up against issues with the windows builds: https://github.com/arobrien/nbstripout/pull/3

A fundamental issue is having tests which require the bash shell to work in a very specific way.

On the other hand, I had another go at testing git integration using built in pytester fixtures, with good success, I think. I'll do up a PR based on this, and make the bash diff test posix-only:
https://github.com/arobrien/nbstripout/blob/arobrien/moretesting/tests/test_git_integration.py

**Comment by kynan** [comment]
Great progress, thanks!
