### ISSUE TITLE
ENH: Provide way of marking cells to keep output.

### ISSUE THREAD

**Issue by mforbes** [kynan/nbstripout#17]
In many of my notebooks I have an initialization cell who's output provides important formatting information (such as MathJaX macro definitions).  It would be nice to be able to somehow signal `nbstripout` to keep certain cells.

This should probably use some sort of [cell metadata](https://github.com/ipython/ipython/wiki/IPEP-20:-Informal-structure-of-cell-metadata), but perhaps could use some sort of pragma:

```
# nbstripout: keep
```

for example.

**Comment by mforbes** [comment]
There is a nice [nbextension for initialization cells](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/init_cell) that adds metadata `"init_cell": true` to the cell.  When enabled, these cells will get run on initializing the kernel.  For my needs it would suffice to simply not strip the output from these cells, though it might be better to consider another independent piece of metadata as well.

**Comment by kynan** [comment]
@mforbes This is resolved, right?

**Comment by mforbes** [comment]
Yes.  I thought that putting "Resolves issue #17" in the commit message would mark this as resolved.

**Comment by kynan** [comment]
OK. I think you can use "fixes #17" or "closes #17" (without mentioning issue).
