### ISSUE TITLE
No valid notebook detected

### ISSUE THREAD

**Issue by Koncopd** [kynan/nbstripout#190]
I get `No valid notebook detected` on nbstripout of all my notebooks with nbstripout 0.7.0
I use jupyter notebook 6.4.11

Is it not compatible anymore?

**Comment by Koncopd** [comment]
[test-notebook.json](https://github.com/kynan/nbstripout/files/14157190/test-notebook.json)
Example notebook where it fails, changed the file type to be able to attach.

**Comment by kynan** [comment]
Thanks for reporting. I can reproduce the issue. That's a major regression, sorry for not catching this!

I'll release 0.7.1 with a fix shortly and will yank 0.7.0 from PyPI.

**Comment by Koncopd** [comment]
Thank you.

**Comment by kynan** [comment]
@Koncopd Release is out, can you please verify?
