### ISSUE TITLE
required = true by default or make doc more explicit about it

### ISSUE THREAD

**Issue by memeplex** [kynan/nbstripout#191]
By default the filter is not required:

> One use of the content filtering is to massage the content into a shape that is more convenient for the platform, filesystem, and the user to use. For this mode of operation, the key phrase here is "more convenient" and not "turning something unusable into usable". [...] Another use of the content filtering is [...] turn it into a usable form upon checkout. These two filters behave differently, and by default, a filter is taken as the former, massaging the contents into more convenient shape. A missing filter driver definition in the config, or a filter driver that exits with a non-zero status, is not an error but makes the filter a no-op passthru. [...] You can declare that a filter turns a content that by itself is unusable into a usable content by setting the filter.<driver>.required configuration variable to true.

Even a slight error in the configuration (e.g. if nbstripout changes location and is not found by git) may silently skip nbstripout. This is rather dangerous, since once big blobs are in the repo it's not easy to cleanup history, specially if it was already pushed to other remotes.

You mention `required = true` but just for manual installation at the bottom of the README.

Please make it the default mode of operation.

**Comment by kynan** [comment]
Your citation appears to be from the [`gitattributes` documentation](https://git-scm.com/docs/gitattributes#_filter). The point you raise makes sense to me. Are there any issues / downsides from making the filter `required` by default? As this is a behaviour change I want to make sure other users won't be surprised or negatively affected.

**Comment by memeplex** [comment]
> Your citation appears to be from the [gitattributes documentation](https://git-scm.com/docs/gitattributes#_filter).

Right, sorry I forgot to add the link.

> Are there any issues / downsides from making the filter required by default? 

I think the difference of behavior will be just on the conservative side. It's hard to think about a "best effort" use case in which you don't care if a 20 MB notebook gets accidentally pushed to your history. We have had episodes like this at the office and they became nightmarish once the changes were spread.

**Comment by kynan** [comment]
Sorry to hear that this has already caused you pain 😞 Would you be interested in sending a PR for this?

**Comment by memeplex** [comment]
> Sorry to hear that this has already caused you pain 😞 

Nah, no problem, it hasn't been like that, mostly people that forgot to install pre-commit hooks, not even filters. But the consequences are the same.


> Would you be interested in sending a PR for this?

Is it just adding

```python
check_call(git_config + ['filter.nbstripout.required', 'true'])
```

[here](https://github.com/kynan/nbstripout/blob/883d871acc4f5c81c781eeae1d074ab2b2937490/nbstripout/_nbstripout.py#L202C9-L202C69)?

**Comment by kynan** [comment]
Yes, that and the equivalent reverse operation in `uninstall`. Ideally also a test, though I'm not entirely sure what the best way to test this would be.

**Comment by kynan** [comment]
@memeplex Are you still interested in sending a PR for this?

**Comment by kynan** [comment]
It is actually a fairly simple change, so I'll implement this myself for the upcoming 0.8.1 release.
