### ISSUE TITLE
Pip install on Anaconda doesn't work

### ISSUE THREAD

**Issue by clenchedteeth** [kynan/nbstripout#20]
Running on Anaconda for windows results in the following:
`C:\Anaconda>pip install nbstripoutput`
`Collecting nbstripoutput
  Could not find a version that satisfies the requirement nbstripoutput (from ve
rsions: )
No matching distribution found for nbstripoutput`
Any idea how I could get this to work? Thanks!

**Comment by kynan** [comment]
You misspelled the package name: `pip install nbstripout`
