### ISSUE TITLE
Use pytest-cram

### ISSUE THREAD

**Issue by kynan** [kynan/nbstripout#22]
@tbekolay has recently released [pytest-cram](https://pypi.python.org/pypi/pytest-cram) on PyPI. Should we be using this instead of bundling our own @mforbes?

**Comment by mforbes** [comment]
It seems to work.  I don't see any reason to keep our own bundle.

**Comment by mforbes** [comment]
Do you need cram 7.0 for some reason or should we just let `pytest-cram` install whatever version it likes?

**Comment by mforbes** [comment]
There are some issues with Travis... not sure how to fix right now.

**Comment by kynan** [comment]
The issue is travis-ci/travis-ci#5635. We need to upgrade pytest to >= 2.8 since that's required by pytest-cram. I've fixed that.
