### ISSUE TITLE
Support installing to .gitattributes?

### ISSUE THREAD

**Issue by jluttine** [kynan/nbstripout#25]
Hi, this is a great tool, thanks! I suppose currently `nbstripout install` installs to `.git/info/attributes`. Would it be possible to support installing to `.gitattributes` with some flag? For instance, `nbstripout install --attributes=.gitattributes` or something better. Of course, one can just run `mv .git/info/attributes .gitattributes` but still it'd be just a nice little polishing to support both installing options. What do you think?

**Comment by kynan** [comment]
Great suggestion! That should not be hard to implement, will look into it.
