### ISSUE TITLE
Can we have a `--is_installed` check?

### ISSUE THREAD

**Issue by michaelaye** [kynan/nbstripout#29]
I'm loosing track where I have nbstripout in use and where not.
Could we have a little check run like:
``nbstripout --is_installed``
that simple returns: "nbstripout is installed in this repo" or "nbstripout is not installed in this repo" respectively?
Would be great, thanks!

**Comment by kynan** [comment]
Yes, good idea, shouldn't be hard to implement, will have a look.

**Comment by kynan** [comment]
@michaelaye I'd prefer to follow the GNU convention i.e. use `--is-installed`.

Rather than printing a message I'd rather use the exit / status code i.e. 0 if installed, 1 if not installed, what do you think?

Maybe we could have another switch e.g. `--status` to print a summary like you suggest, maybe also including details on the filter.

**Comment by kynan** [comment]
@michaelaye I have implemented the status code (without output). Any thoughts?

**Comment by michaelaye** [comment]
Thanks, I'd still like a version with a text output though. The whole idea of this is for non-hackers to be able to do this, and those most likely don't know anything about GNU exit codes.

**Comment by themiurgo** [comment]
This functionality is already documented in the README, but it's not yet present. Maybe it's worth removing from the current documentation until it's implemented?

**Comment by kynan** [comment]
@themiurgo The feature is in master but not yet released. I'll implement the status functionality @michaelaye was asking for and cut a new release.

**Comment by kynan** [comment]
@themiurgo 0.2.7 is released!

**Comment by kynan** [comment]
@michaelaye I've added a `--status` command, please let me know if that is satisfactory and reopen this issue if not!

**Comment by michaelaye** [comment]
Okay, thanks. major issue i have recently is the performance though. everytime i go into a repo with lots of notebooks, it takes 5 seconds before i get my prompt back, which can be annoying...
I'm wondering if the official PreProcessor of the notebook tools is faster than your manual filtering?

**Comment by kynan** [comment]
@michaelaye Yes, speed is an issue indeed. Want to create an issue for it?

**Comment by michaelaye** [comment]
#33 ;)
