### ISSUE TITLE
Stripping other metadata (execute time) 

### ISSUE THREAD

**Issue by jdriordan** [kynan/nbstripout#34]
I'm using the (hugely useful) `Execute Time` nbextension, which produces cell metadata like this:

    {
     "cell_type": "code",
     "execution_count": null,
     "metadata": {
      "ExecuteTime": {
       "end_time": "2016-08-15T11:49:40.736068",
       "start_time": "2016-08-15T11:49:40.145965"
      },
      "code_folding": [],
      "collapsed": false
     },
     "outputs": [],
     "source": []
    }

But naturally I end up with a load of changes seen by git after running `nbstripout` because of re-running the cells and updating the `ExecuteTime` field. Would you accept a pull request explicitly stripping this out, or alternatively one which strips all but whitelisted metadata entries?

**Comment by kynan** [comment]
I suppose stripping all but whitelisted metadata would make sense. How do you envision configuring that whitelist?

**Comment by kynan** [comment]
@jdriordan, are you still planning to submit a pr for this?

**Comment by jdriordan** [comment]
Sorry for the delay. One way to do a whitelist would be to start with those given in [the format spec](https://nbformat.readthedocs.io/en/latest/format_description.html#metadata), i.e.

- `kernelspec`
- `collapsed`
- `autoscroll`
- `deletable`
- `format`
- `name`
- `tags`
- `isolated`

along with those used by `nbstripout`,

- `init_cell`
- `keep_output`
- `scrolled`

People seem to be using metadata for other various things in the wild (author/description etc.) and it's also used by some extensions (which could register themselves on the whitelist, in theory). 

Having looked at all this I've managed to convince myself a blacklist is a more sensible option (since other metadata doesn't change in a useless way like this does. So I've ended up making a really simple change that just strips this one field (but could trivially do others too). 

PR submitted.

**Comment by kynan** [comment]
I agree with your rationale about blacklisting rather than whitelisting. PR merged!

**Comment by michaelaye** [comment]
time to release maybe? ;)

**Comment by kynan** [comment]
@michaelaye it is indeed, let me cut a new release!
