### ISSUE TITLE
Missing trailing newline

### ISSUE THREAD

**Issue by cthoyt** [kynan/nbstripout#36]
Line [170 of nbstripout.py](https://github.com/kynan/nbstripout/blob/master/nbstripout.py#L170) reads as `f.write('\n*.ipynb filter=nbstripout')`. With the context manager on line 169, this appends the filter to `.gitattributes` without a trailing new line character. 

This might be a matter of opinion, but it would be nice to have a trailing new character, especially because this line is being appended to the end of the file. Also, since the script includes `from __future__ import print_function`, this line could be rewritten as `print('\n*.ipynb filter=nbstripout', file=f)` to accomplish this.

**Comment by kynan** [comment]
Good suggestion, I'll implement that!
