### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by kynan** [kynan/nbstripout#4]
Some simple unit tests to make sure we don't accidentally break stuff.

**Comment by mforbes** [comment]
[cram](https://pypi.python.org/pypi/cram) might be a good tool for this.  (It is based on the tool used to test mercurial.)

**Comment by kynan** [comment]
OK, will take a look. I'm a big fan of [pytest](http://pytest.org).

**Comment by kynan** [comment]
Have started with a trivial [Travis](http://travis-ci.org) config that only runs [flake8](https://gitlab.com/pycqa/flake8).

**Comment by mforbes** [comment]
I added a small modules `pytest_cram.py` that allows you to run cram from `pytest` as well as a small (dummy) test that runs mercurial.  I am not finished with my hooks yet, but you should be able to simply modify this to run `git` tests.

**Comment by kynan** [comment]
@mforbes Great, do you want to pr this?

**Comment by mforbes** [comment]
Sure. Could you please remind me what I have to do to rebase my changes on yours or shall I just submit the PR as is?  (I still find ``git`` somewhat confusing and am not sure of the magic incantation needed to pull in your changes and then rebase mine...)

**Comment by kynan** [comment]
Ah, yes, sure! Assuming my repo is `upstream` you do

    git fetch upstream
    git rebase upstream/master
    git push --force

**Comment by mforbes** [comment]
Done.  (thanks)

**Comment by kynan** [comment]
We have some simple tests now (to be extended!), hence closing.
