### ISSUE TITLE
Differences in handling of "collapsed" metadata?

### ISSUE THREAD

**Issue by ar-jan** [kynan/nbstripout#50]
I have something weird going on with the status of the `"collapsed": true` (and `false`) lines in a git diff of a .ipynb file.

I did a commit, nbstripout did its work, and I can see that what was commited contains `   "metadata": {     "collapsed": false    },` (as seen with `git diff HEAD^` as well as on the remote Gitlab repo).

I pulled this commit on another computer. Now when I do a `git diff`, I get this:
```
    "cell_type": "code",
    "execution_count": null,
    "metadata": {
-    "collapsed": true
+    "collapsed": false
    },
    "outputs": [],
    "source": [
```

So the current state of the file is correct, but it thinks the repository contains this line as `"collapsed": true`, even though when I do `git diff HEAD^` i can see that commited line contains "false". Doing `git checkout .` does not change anything.

Is it possible that nbstripout's handling is not symmetric in committing/checkout vs. status and diff?

P.S. On both computers I'm using Anaconda (Python 3.5.2), with nbstripout 0.2.9 from conda-forge. Config:

$ `nbstripout --status`

```
nbstripout is installed in repository b'/path/to/my/repo'

Filter:
  clean = b'/path/to/anaconda3/bin/python /path/to/anaconda3/lib/python3.5/site-packages/nbstripout.py'
  smudge = b'cat'
  required = b'true'

Attributes:
  b'*.ipynb: filter: nbstripout'
```

**Comment by kynan** [comment]
Could you please try upgrading to 0.3.0? The collapsed state should be ignored as of that version.

**Comment by orenshk** [comment]
I am on 0.3.0 and can confirm this is still cropping up, though a little different:

`   {
    "cell_type": "code",
    "execution_count": null,
-   "metadata": {
-    "collapsed": true
-   },
+   "metadata": {},
    "outputs": [],
    "source": [
`

**Comment by kynan** [comment]
@ar-jan were you able to test this?

**Comment by ar-jan** [comment]
Thanks, looks like this works now.
