### ISSUE TITLE
Only output should be kept for keep_output and init_cell

### ISSUE THREAD

**Issue by reidpr** [kynan/nbstripout#52]
Currently, `nbstripout` ignores `keep_output` and `init_cell` cells entirely. However, this means that lots of stuff beyond the output stays, such as `execution_count`. I think keeping this does not meet the design goals, and it can cause Git conflicts.

Feature request: Treat these two types of cells normally, except keep the output.

**Comment by kynan** [comment]
Good idea! This could be addressed in #56

**Comment by jpeacock29** [comment]
Added a patch for this in #56

**Comment by jpeacock29** [comment]
Pull #56 should close this now.
