### ISSUE TITLE
Programmatically run nbstripout and output new file.

### ISSUE THREAD

**Issue by stanleyng8** [kynan/nbstripout#57]
I am trying to run nbstripout programmatically within a Python script and create a new file from the input file (and not in-place). The documentation doesn't have this use case covered. Is there a way I can do it?

**Comment by kynan** [comment]
There is a (as you rightly point out undocumented) way of doing it programmatically - [do what is done in `main()`](https://github.com/kynan/nbstripout/blob/master/nbstripout.py#L334-L341). Something like this (untested):
```python
import io
from nbstripout import strip_output, read, write, NO_CONVERT

if __name__ == '__main__':
    filename = ...
    outfile = ...
    with io.open(filename, 'r', encoding='utf8') as f:
        nb = read(f, as_version=NO_CONVERT)
    nb = strip_output(nb)
    with io.open(outfile, 'w', encoding='utf8') as f:
        write(nb, f)
```

**Comment by stanleyng8** [comment]
I tried the above in Python3 and am getting the following error. 
  File "/Users/stanley/anaconda3/envs/py36/lib/python3.6/site-packages/nbstripout.py", line 96, in <module>
    output_stream = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
AttributeError: 'OutStream' object has no attribute 'buffer'

I looked at the nbstripout.py code and the code is specifically for Python3 yet this is where the error is coming from. Any ideas for a fix?

**Comment by kynan** [comment]
Are you trying the import from *within* a notebook? This will *not work* because `sys.stdout` is a `ipykernel.iostream.OutStream` in that case.

**Comment by psthomas** [comment]
I was trying to do something similar and might have a solution.  If you want to do this from within a notebook, it's possible to run nbstripout as a part a bash command in a cell:
```python
# Both original and the cleaned example are in the current working directory
notebook_path = './notebook.ipynb'
cleaned_path = './notebook_clean.ipynb'

# Bash commands within notebooks are preceeded by "!"
!cat {notebook_path} | nbstripout > {cleaned_path}
```
 I've been running a command like this in a cell to make it more versatile and provide some feedback:
```python
import os
from datetime import datetime

notebook_path = os.path.join(os.getcwd(),'notebook.ipynb')
cleaned_path = os.path.join(os.getcwd(),'notebook_clean.ipynb')

!cat {notebook_path} | nbstripout > {cleaned_path}

date_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
print('{0} Cleaned file created at: {1}'.format(date_str, cleaned_path))
```
```
2017-06-23 12:57:40 Cleaned file created at: <current directory>/notebook_clean.ipynb
```

**Note:** I think there might be an error in readme.rst because the [shell pipeline example](https://github.com/kynan/nbstripout/blame/master/README.rst#L61) doesn't use `cat` while the [docstring in nbstripout.py](https://github.com/kynan/nbstripout/blob/master/nbstripout.py#L29) does.  I can open a separate issue if needed.

**Comment by stanleyng8** [comment]
Thanks for the comments. I was running nbstripout with Python 3.6 as a script and not a notebook.

**Comment by kynan** [comment]
@stanleyng8 I can not reproduce this issue: have tried with Python 3.6 from anaconda. Which nbstripout version are you using?

**Comment by stanleyng8** [comment]
Thanks Florian but I have decided not to pursue this avenue any further.
