### ISSUE TITLE
pip 0.3.0 version is outdated

### ISSUE THREAD

**Issue by jykim** [kynan/nbstripout#60]
I found that the pip version doesn't have -t switch so had to use the git version.

$ nbstripout -t my_notebook.ipynb 
usage: nbstripout [-h] [--install] [--uninstall] [--is-installed] [--status]
                  [--attributes FILEPATH] [--version] [--force]
                  [files [files ...]]
nbstripout: error: unrecognized arguments: -t
$ pip install --upgrade nbstripout
Requirement already up-to-date: nbstripout in /Users/jinyoung.kim/Package/Conda36/anaconda/envs/py27/lib/python2.7/site-packages
$ nbstripout --version
0.3.0

**Comment by kynan** [comment]
Yes, I'll tag a new release, sorry for the delay.

**Comment by kynan** [comment]
0.3.1 has been released today!
