### ISSUE TITLE
nbstripout crashes when input is empty

### ISSUE THREAD

**Issue by reidpr** [kynan/nbstripout#66]
**Steps to reproduce**

    $ cat /dev/null | nbstripout

**Expected results**

Zero bytes of output; exit code 0.

**Actual results**

Stack trace; exit code 1. E.g.:

```
Traceback (most recent call last):
  [...]
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [...]
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
```

**Comments**

Version 0.3.1 on OS X, installed with Conda.

This make it harder to recover from bad Git commits, e.g. caused by #55, because Git won't do anything unless its filters exit successfully. One must disable the filter, untangle things, and then re-enable it.

Thank you!

**Comment by kynan** [comment]
This will be fixed in 0.3.2
