### ISSUE TITLE
`git diff` not working after nbstripout installation

### ISSUE THREAD

**Issue by ggrrll** [kynan/nbstripout#77]
Hi ,

thanks for this tool!

I am on mac os 10.13.4 and git 2.15.1.

I tried both `nbstripout --install` and `nbstripout --install --attributes .gitattributes` but in both cases `git diff` returns me nothing after I modify my notebook - it's weird as indeed the change  is captured for instance by the github gui (the repo is conneted to github)

any idea? 

Thanks

**Comment by ggrrll** [comment]
solved thanks to https://github.com/ar-jan comments'on #69

**Comment by kynan** [comment]
0.3.2 is now released!

**Comment by hyuntae0117** [comment]
I have this bug also
my nbstripout version is 0.3.3 (installed by conda)

after nbstripout --install
git diff shows nothing

**Comment by kynan** [comment]
@hyuntae0117 sorry for the late reply: what platform are you on? And which Python version?
