### ISSUE TITLE
Needs uninstall

### ISSUE THREAD

**Issue by michaelaye** [kynan/nbstripout#8]
Uninstall would be helpful for people just trying things out.

**Comment by mforbes** [comment]
Do you mean uninstalling the git hooks?  `pip uninstall nbstripout` should remove the package itself.  I don't think `pip` allows this to be customized though, so one would probably have to run a separate uninstall command to clean out any git hooks.

**Comment by michaelaye** [comment]
Well, yes, but the git hooks are installed via `nbstripout install`, hence there's a `nbstripout uninstall` missing to remove the hooks.

**Comment by kynan** [comment]
Very good suggestion, will look into it.
