### ISSUE TITLE
Possible to design a "smudge" git filter that reverses the stripping process?

### ISSUE THREAD

**Issue by lukelbd** [kynan/nbstripout#89]
I work on multiple servers for my research, and use git to sync my project repository between these servers servers. Sometimes this means I want to work on the same jupyter notebook on different servers. The problem with this is, if I make some changes on server A and want just the *code* changes on server B, after pushing and pulling the server B output is stripped.

Would it be possible to design a "smudge" filter that *reverses* the stripping process -- i.e., when a merge between a stripped repository file and un-stripped work directory file is performed, the code changes are made but the output is preserved?

I'm guessing the answer is: this is super non-trivial. But just a thought. An example use case: you want to append a couple cells onto a large notebook whilst on server B, then transport those changes to server A without deleting the output of the (completely untouched) rest of the notebook.

**Comment by kynan** [comment]
Not saying this is not doable, but I don't think `nbstripout` is the tool for this job. Have you looked at https://github.com/jupyter/nbdime ?

**Comment by kynan** [comment]
@lukelbd is this still an issue for you?

**Comment by lukelbd** [comment]
@kynan I now use `jupytext`, which supports this behavior. If cells are added to the jupytext `.py` file associated with an open `.ipynb` notebook, the notebook output is not deleted.
