### ISSUE TITLE
Public API changes (0.3.3 -> 0.3.4)?

### ISSUE THREAD

**Issue by paugier** [kynan/nbstripout#96]
With version 0.3.3, it was possible to do:

```
with io.open(filename, "r", encoding="utf8") as f:
    nb = nbstripout.read(f, as_version=nbstripout.NO_CONVERT)
nb = nbstripout.strip_output(nb, keep_output, keep_count)
with io.open(filename, "w", encoding="utf8") as f:
    nbstripout.write(nb, f)
```

With 0.3.4, it seems that this API is no longer supported (`read`, `write`, `NO_CONVERT` are now in `nbstripout._nbstripout`). Nothing about this in CHANGELOG.rst... No DeprecationWarning...

How this code should be rewritten for nbstripout >= 0.3.4 ? It does not seem to be nice to have to use the private API `nbstripout._nbstripout`.

**Comment by kynan** [comment]
`read`, `write` and `NO_CONVERT` are actually imported from `nbformat` and were never intended to be part of the public API. Does the following work for you?

```
import io
import nbformat
import nbstripout

with io.open(filename, "r", encoding="utf8") as f:
    nb = nbformat.read(f, as_version=nbformat.NO_CONVERT)
nb = nbstripout.strip_output(nb, keep_output, keep_count)
with io.open(filename, "w", encoding="utf8") as f:
    nbformat.write(nb, f)
```

**Comment by kynan** [comment]
@paugier Does my suggestion work for you?

**Comment by paugier** [comment]
Yes! Thank you for your answer and for nbstripout!
